name: "Build and Release"

on:
  workflow_dispatch:
    push:
      branches:
        - master
      paths-ignore:
        - '**/.gitignore'
        - '**/README.md'

env:
  WIN_OUTPUT_PATH: WsjtxGps/bin/Release/net8.0/win-x64/publish/
  LINUX_OUTPUT_PATH: WsjtxGps/bin/Release/net8.0/linux-x64/publish/
  LINUX_ARM_OUTPUT_PATH: WsjtxGps/bin/Release/net8.0/linux-arm/publish/
  LINUX_ARM64_OUTPUT_PATH: WsjtxGps/bin/Release/net8.0/linux-arm64/publish/
  OSX_OUTPUT_PATH: WsjtxGps/bin/Release/net8.0/osx-x64/publish/
  OSX_ARM_OUTPUT_PATH: WsjtxGps/bin/Release/net8.0/osx-arm64/publish/
  
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
          source-url: https://nuget.pkg.github.com/jeffu231/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Display dotnet version
        run: dotnet --version
        
      - name: Install Dependencies
        run: dotnet restore
        
      - name: Setup git
        run: |
          git config --local user.email "git@k9kld.org"
          git config --local user.name "git" 
          
      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Versioning
        id: versionize
        run: versionize --aggregate-pre-releases --skip-dirty
        continue-on-error: true

      - name: Test if release required
        if: steps.versionize.outcome != 'success'
        run: echo "Skipping Release. No release required."

      - name: Push changes to GitHub
        if: steps.versionize.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Get current version
        if: steps.versionize.outcome == 'success'
        run: echo "VERSION=$(versionize inspect)" >> $GITHUB_ENV

      - name: Get current changelog
        if: steps.versionize.outcome == 'success'
        run: |
          echo "$(versionize changelog)" > latest_changelog.md
          cat latest_changelog.md
        shell: bash

      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish win-x64
        if: steps.versionize.outcome == 'success'
        run: dotnet publish -c Release -r win-x64
        
      - name: Publish linux-x64
        if: steps.versionize.outcome == 'success'
        run: dotnet publish -c Release -r linux-x64
        
      - name: Publish linux-arm
        if: steps.versionize.outcome == 'success'
        run: dotnet publish -c Release -r linux-arm
        
      - name: Publish linux-arm64
        if: steps.versionize.outcome == 'success'
        run: dotnet publish -c Release -r linux-arm64
        
      - name: Publish osx-x64
        if: steps.versionize.outcome == 'success'
        run: dotnet publish -c Release -r osx-x64
        
      - name: Publish osx-arm64
        if: steps.versionize.outcome == 'success'
        run: dotnet publish -c Release -r osx-arm64
        
      - name: Create win-x64 zip file
        if: steps.versionize.outcome == 'success'
        uses: papeloto/action-zip@v1.2
        with:
          files: ${{ env.WIN_OUTPUT_PATH }}
          dest: WsjtxGps-win-x64.zip
          
      - name: Create linux-x64 zip file
        if: steps.versionize.outcome == 'success'
        uses: papeloto/action-zip@v1.2
        with:
          files: ${{ env.LINUX_OUTPUT_PATH }}
          dest: WsjtxGps-linux-x64.zip
          
      - name: Create linux-arm zip file
        if: steps.versionize.outcome == 'success'
        uses: papeloto/action-zip@v1.2
        with:
          files: ${{ env.LINUX_ARM_OUTPUT_PATH }}
          dest: WsjtxGps-linux-arm.zip
          
      - name: Create linux-arm64 zip file
        if: steps.versionize.outcome == 'success'
        uses: papeloto/action-zip@v1.2
        with:
          files: ${{ env.LINUX_ARM64_OUTPUT_PATH }}
          dest: WsjtxGps-linux-arm64.zip
          
      - name: Create osx-x64 zip file
        if: steps.versionize.outcome == 'success'
        uses: papeloto/action-zip@v1.2
        with:
          files: ${{ env.OSX_OUTPUT_PATH }}
          dest: WsjtxGps-osx-x64.zip
          
      - name: Create osx-arm64 zip file
        if: steps.versionize.outcome == 'success'
        uses: papeloto/action-zip@v1.2
        with:
          files: ${{ env.OSX_ARM_OUTPUT_PATH }}
          dest: WsjtxGps-osx-arm64.zip
          
      - name: List files in the workspace
        if: steps.versionize.outcome == 'success'
        run: | 
          ls -lah
            
      - name: Create Release
        if: steps.versionize.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          files: "WsjtxGps*.zip"
          body_path: latest_changelog.md
          name: "Release ${{env.VERSION}}"
          tag_name: "v${{env.VERSION}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      